# config.yml
finnhub:
  api_key: "${FINNHUB_API_KEY}"
symbols:
  - AAPL
  - GOOGL
  - MSFT
  - AMZN

influxdb:
  url: http://influxdb:8086
  token: my-super-secret-token
  org: my-org
  bucket: my-bucket
scheduler:
  interval_minutes: 30
cache:
  ttl_days: 1
  ttl_minutes: 29
rate_limit:
  max_calls_per_min: 5
